// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eofxxvsfyvwqjyattgbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvZnh4dnNmeXZ3cWp5YXR0Z2JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTk5NDEsImV4cCI6MjA2MTA3NTk0MX0.0-qmKrBOV-fLzlxIiH4NTuQvdpTLrAmqc3mfXMs1sGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);